[project]
name = "Clarity-xbtc-send-plus"
description = "A Clarinet project for xBTC send many functionality"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
[contracts.xbtc-send-many]
path = "contracts/xbtc-send-many.clar"
clarity_version = 4
epoch = "3.3"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
